apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrinest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrinest
  template:
    metadata:
      labels:
        app: nutrinest
    spec:
      containers:
        - name: nutrinest
          image: deepikajayaraman/nutrinest:latest
          ports:
            - containerPort: 8080
